%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.20.3 on {{2016,6,3},{0,59,36}}

-ifndef(dcos_dns_dcos_dns_pb).
-define(dcos_dns_dcos_dns_pb, true).

-define(dcos_dns_dcos_dns_pb_gpb_version, "3.20.3").

-ifndef('NAVSTAR_DNS_ARECORD_PB_H').
-define('NAVSTAR_DNS_ARECORD_PB_H', true).
-record(dcos_dns_arecord,
        {ip                     :: non_neg_integer() % = 1, 32 bits
        }).
-endif.

-ifndef('NAVSTAR_DNS_SRVRECORD_PB_H').
-define('NAVSTAR_DNS_SRVRECORD_PB_H', true).
-record(dcos_dns_srvrecord,
        {priority               :: integer(),       % = 1, 32 bits
         weight                 :: integer(),       % = 2, 32 bits
         target                 :: binary(),        % = 3
         port                   :: integer()        % = 4, 32 bits
        }).
-endif.

-ifndef('NAVSTAR_DNS_RECORD_PB_H').
-define('NAVSTAR_DNS_RECORD_PB_H', true).
-record(dcos_dns_record,
        {name                   :: binary(),        % = 1
         type                   :: 'A' | 'SRV',     % = 2, enum Record.Type
         srv_record             :: #dcos_dns_srvrecord{} | undefined, % = 3
         a_record               :: #dcos_dns_arecord{} | undefined % = 4
        }).
-endif.

-ifndef('NAVSTAR_DNS_ZONE_PB_H').
-define('NAVSTAR_DNS_ZONE_PB_H', true).
-record(dcos_dns_zone,
        {name                   :: binary(),        % = 1
         records = []           :: [#dcos_dns_record{}] % = 2
        }).
-endif.

-endif.
